[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = 'tips_trainer'
version = '0.1'
dependencies = ['tensorflow_io', 'google-cloud-aiplatform', 'db-dtypes', 'protobuf>=4.25.1']
description = 'Training Package'
authors = [{name = 'statmike'}]
